### ISSUE TITLE
Animated Hero Squares

### ISSUE THREAD

**Issue by Shivansh-22866** [AayushPaigwar/Innovate-with-Open-Soucre#117]
Hey @AayushPaigwar,
I was playing around the website a bit more, and I thought of an idea, how about we animate the hero section of this
website as a feature?

Each square object being an interactive component would look sweet. I tried to do something like that here
[Screencast_20241008_003712.webm](https://github.com/user-attachments/assets/fc4152d1-d9cf-436b-8dce-238e0472cb8f)

If you like this idea, assign this issue to me under hacktoberfest-accepted and hacktoberfest so I can start working on this feature

**Comment by AayushPaigwar** [comment]
Instead of this, can you implement the same thing with the boxes at the same position, and will keep blinking at a very low effect automatically instead of hovering it. 
Have a Try!!

**Comment by Shivansh-22866** [comment]
Yeah, I can get the automatic blinking effect, I would just need to position the squares a little bit so that it matches the background in the same way. 
I think I can work on this, so yeah, that can be possible

**Comment by AayushPaigwar** [comment]
Try It, if works then GTG! ✨

**Comment by Shivansh-22866** [comment]
Also, add hacktoberfest-accepted label if possible
