### ISSUE TITLE
Feat : Horizontal Infinity Scroll Effect in Contributor Section

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#122]
## Description:
Implement a horizontal infinity scroll effect in the Contributor section to enhance user experience. This will allow seamless browsing of contributors without pagination.

### Requirements:
- Horizontal scrolling layout for the Contributor section.
- Responsive design for various screen sizes.
- Don't remove the existing cards, add infinity above the cards

#### Preview:

![1_L0gNy34NLgQ3aUv5Wsh6Ug](https://github.com/user-attachments/assets/8384432e-53c8-425b-bee4-656e847fa1e4)

### Acceptance Criteria:

- Continuous horizontal scrolling of contributors.
- Seamless loading of new contributors.

**Comment by Sachita007** [comment]
Could you assign this to me? I would like to work on it.

**Comment by AayushPaigwar** [comment]
Assigning you the issue. Please make sure to add a video in PR.

**Comment by AayushPaigwar** [comment]
Any Update? @Sachita007

**Comment by AayushPaigwar** [comment]
#137 Fixed
