### ISSUE TITLE
Feat : Search Functionality in the Contributor's Section

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#123]
## Description:
Implement a search bar in the Contributor section to allow users to easily find contributors by name and other attributes.

## Requirements:

- Add a search bar at the top of the Contributor section.
- Support dynamic search results as users type.
- Ensure responsiveness and user-friendliness on all devices.

## Acceptance Criteria:

- Users can search contributors in real-time.
- Clear display of search results without performance issues.

**Comment by ragul1697** [comment]
Hey @AayushPaigwar, I would like to take this task.

**Comment by AayushPaigwar** [comment]
Sure! Go for it... 🔥
Make sure to provide a screen recording in the PR

**Comment by AayushPaigwar** [comment]
#139 Fixed
