### ISSUE TITLE
 Add Documentation for Steps to Add Personal Blog

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#130]
## Description:
  
- Update the `Readme.md` and `Contributing.md` files to include clear, concise instructions on how users can add their personal blog to the project. 

- The documentation should provide a step-by-step guide for ease of use and contribution. 

- Refer to the [JSON format](https://innovate-with-opensource.netlify.app/#howToContribute) for structuring the blog submission process.

- Make sure to add screenshot in PR

**Comment by Atharva-Werulkar** [comment]
Hello,

I'd like to work on updating the Readme.md and Contributing.md to include clear steps for users to add their blogs, following the JSON structure. I'll also include screenshots in the PR to ensure the process is easy to follow.

Best regards,
Atharva Werulkar

**Comment by AayushPaigwar** [comment]
Assigning you the issue
