### ISSUE TITLE
Improving the UI of navbar 

### ISSUE THREAD

**Issue by rishabh-bijalwan12** [AayushPaigwar/Innovate-with-Open-Soucre#34]
The navbar is not looking attractive. The links inside the navbar are not visible when we hover over them i can make it attractive

![Screenshot 2024-05-10 161342](https://github.com/jarvis-ghrce/Innovate-with-Open-Soucre/assets/116650217/7f2a0b53-a641-4004-be8a-11747f0d918e)

**Comment by rishabh-bijalwan12** [comment]
Kindly assign me this issue under GSSOC'24

**Comment by AayushPaigwar** [comment]
@rishabh-bijalwan12  
You can contribute to this if you wanted to, but this project is not under GSSoC.
Kindly check the websites for the projects.


[Website Link](https://gssoc.girlscript.tech/project)
