### ISSUE TITLE
Footer: Add "Help Wanted?" text button which redirects to the LinkedIn Account for help

### ISSUE THREAD

**Issue by rko0211** [AayushPaigwar/Innovate-with-Open-Soucre#37]
At present the project has no Contact page . So kindly assign me this task under **GSSOC24** .

Thank you.

**Comment by AayushPaigwar** [comment]
You are always welcome to contribute to this project.
but this project is not under GSSOC24.

**Comment by GIRIRAJSHANKAR27** [comment]
Assign me this problem under hacktoberfest

**Comment by AayushPaigwar** [comment]
Assigned to you, Go for it! 🚀

**Comment by AayushPaigwar** [comment]
# ❗️Migrating our whole website from _Rect + Vite -> Next.js_

## ❗️We request that you update your forked repository to add contributions accordingly.

@GIRIRAJSHANKAR27

**Comment by Shivansh-22866** [comment]
@AayushPaigwar I would like to work on this issue. Is it still open to work upon?

**Comment by AayushPaigwar** [comment]
Instead of adding a contact page, you can add something like a text button in the footer or navbar, saying -> "Help Wanted?", which will redirect to the LinkedIn or mail id

**Comment by Shivansh-22866** [comment]
@AayushPaigwar can you assign me the issue then? Just give some more details of how it should look like, etc. and then I can start working on it

**Comment by AayushPaigwar** [comment]
Issue fixed #115

**Comment by Shivansh-22866** [comment]
Hey! I have a little doubt, I was just going through my Hacktoberfest account and realized that the PR is not accepted yet.
![Screenshot_20241007_190525](https://github.com/user-attachments/assets/c506e0ca-74b8-42fe-8691-b4fe35b97a22)
May I know what could possibly be the reason behind this?
