### ISSUE TITLE
Navbar is not working 

### ISSUE THREAD

**Issue by rko0211** [AayushPaigwar/Innovate-with-Open-Soucre#38]
In mobile device the navbar of this website is not working . so kindly assign me this task under **GSSOC24**, i want make the navbar design more attractive to the user and responsive for all device .

Thank you

**Comment by AayushPaigwar** [comment]
You are always welcome to contribute to this project.
but this project is not under GSSOC24.

**Comment by thepankajnamotra** [comment]
Assign me, I will fix this

**Comment by AayushPaigwar** [comment]
@spankaj13579  Go for it.

**Comment by AayushPaigwar** [comment]
Any problem while implementing the changes? 
@spankaj13579

**Comment by thepankajnamotra** [comment]
Fixed branch name: **fixed-nav-bar-mob**
navigation for mobile with the help of  hooks also improved CSS structure

**Comment by AayushPaigwar** [comment]
Please sync your branch and push the changes according to the React + Vite

**Comment by Kalpak43** [comment]
@AayushPaigwar I would like to work on this issue.

**Comment by AayushPaigwar** [comment]
Go for it! @Kalpak43 🚀

**Comment by AayushPaigwar** [comment]
# ❗️Migrating our whole website from _Rect + Vite -> Next.js_

## ❗️We request that you update your forked repository to add contributions accordingly.

@Kalpak43
