### ISSUE TITLE
Fix the footer

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#40]
- Please fix the footer and try to make it as given below. 

| Before | Expected |
|--------|--------|
| <img width="1440" alt="Screenshot 2024-05-22 at 3 57 52 PM" src="https://github.com/jarvis-ghrce/Innovate-with-Open-Soucre/assets/90213184/dac19d99-d7c6-4d08-813e-96161e54e024"> | ![](https://i.pinimg.com/564x/08/ff/79/08ff79fc2d39e2e2fe5126300e95de6e.jpg) |

**Comment by SeanAverS** [comment]
Hello. I would like to work on this. Could I please be assigned? Thanks.

**Comment by AayushPaigwar** [comment]
@SeanAverS Go for it. 🚀

**Comment by AayushPaigwar** [comment]
Fixed!  #41
