### ISSUE TITLE
GitHub icons have background color as white, making them invisible.

### ISSUE THREAD

**Issue by ItsMeRaseeca** [AayushPaigwar/Innovate-with-Open-Soucre#42]
Issue : In the user cards, the GitHub icon is having a background color as white, which makes it invisible while hovering on it.

Fix : Changing the background color to darker shade would help enhance the visibility of the icon, thus improving UI.

Please assign this issue to me.

**Comment by AayushPaigwar** [comment]
Assigned @ItsMeRaseeca

**Comment by AayushPaigwar** [comment]
Fixed #43
