### ISSUE TITLE
Docs: Update the readme.md [Contributions steps]

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#48]
### Descriptions:
- Need to update the contribution steps as per the new  code and folder structure.

| Fix this |
|--------|
| ![Screenshot 2024-06-02 at 3 28 33 PM](https://github.com/AayushPaigwar/Innovate-with-Open-Soucre/assets/90213184/28bfe861-63c2-4b1b-9cd7-996f58642424) | 

### Task:

- [ ] Rewrite the contribution steps as per the new folder structure
- [ ] Create a code snippet for contributors, so they can copy and add their name and GitHub profile to it.

**Comment by ghost** [comment]
hey @AayushPaigwar assign me this issue

**Comment by AayushPaigwar** [comment]
@msohailx Go for it! 🚀
