### ISSUE TITLE
Docs : Add steps to run React project in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#64]
## Issue Description: 

- In step 4 of the `README.md` and `CONTRIBUTING.md` files, additional instructions should be provided for setting up and running the React project. 
- These steps may include dependency installation, and running the development server. This will help contributors and users easily set up and run the project locally.

**Comment by theDevSoham** [comment]
Good day @AayushPaigwar . Can I take up this issue if it's available?

**Comment by AayushPaigwar** [comment]
Sure, Assigning you this issue.

**Comment by theDevSoham** [comment]
Thanks a lot @AayushPaigwar

**Comment by HackesticMedusa** [comment]
Please assign me to this issue, I’d like to add the setup and running instructions for the React project.

**Comment by theDevSoham** [comment]
@AayushPaigwar please check I've added PR

**Comment by AayushPaigwar** [comment]
@HackesticMedusa  The issue is already resolved. Please find some bugs or more enhancements and create issues 

Fixed #74
