### ISSUE TITLE
Footer Improvement and Enhancement

### ISSUE THREAD

**Issue by VedantDewangan** [AayushPaigwar/Innovate-with-Open-Soucre#66]
I would like to propose enhancements for the footer section of the project. The current footer lacks visual appeal and functionality. I believe we can improve its design and interactivity to better align with the overall aesthetics of the application.

I am eager to take on this task and would appreciate it if you could assign me to this issue. Thank you!

**Comment by AayushPaigwar** [comment]
Assigning you the issue go for it.

**Comment by AayushPaigwar** [comment]
Closing this issue - #70 (Issue Fixed)
