### ISSUE TITLE
 Implement Hover Effect on Contributor Cards

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#79]
- Add a hover effect to contributor cards to enhance interactivity and user experience.
 -  Provide design suggestions if available.

**Comment by Aiu26** [comment]
@AayushPaigwar can u assign this to me under hacktoberfest?

**Comment by AayushPaigwar** [comment]
Assigned to you, make sure to provide a video/gif of your contribution in PR.

**Comment by AayushPaigwar** [comment]
#84 Issue fixed
