### ISSUE TITLE
Make the website Responsive for mobile view and all viewports

### ISSUE THREAD

**Issue by AayushPaigwar** [AayushPaigwar/Innovate-with-Open-Soucre#80]
- The current application layout does not adapt well to different screen sizes, leading to usability issues on mobile and tablet devices. 
- We need to implement responsive design principles to ensure that the UI components adjust seamlessly across various viewports. This includes:

**Comment by Arshad-ashuu** [comment]
I would like to work on this issue. Can you please assign this to me @AayushPaigwar

**Comment by Arnavpk** [comment]
I can make your website responsive to all viewports. Can you assign me to this issue

**Comment by Dhruv6397** [comment]
I can make it responsive if you allow me to do..?

**Comment by Dhruv6397** [comment]
I can make it responsive if you allow me to do..?

**Comment by AayushPaigwar** [comment]
@Dhruv6397 @Arshad-ashuu The issue is fixed #82  request you to please create a issue to fix bug or website enhancement
