### ISSUE TITLE
Avatar of contributers are same

### ISSUE THREAD

**Issue by nikhil-nandanwar** [AayushPaigwar/Innovate-with-Open-Soucre#85]
As I visit website, I notice that avatar of every contributers are same.
I can change fix it by replacing avatar to their respective github profile photo.
So I request  @AayushPaigwar   assign to me.
Thank you!!

**Comment by AayushPaigwar** [comment]
Assigning you the issue, also give a guide in `readme.md` and `contributing.md` for achieving the GitHub profile photo link.

**Comment by nikhil-nandanwar** [comment]
@AayushPaigwar I have create a pull request please review it. And let me know any changes you want

**Comment by AayushPaigwar** [comment]
Fixed #97
