### ISSUE TITLE
Responsive issue in mobile devices 

### ISSUE THREAD

**Issue by SharizHussain** [AayushPaigwar/Innovate-with-Open-Soucre#94]
Page is overflowing as below 👇 image:

![Screenshot_2024-10-03-00-18-15-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/b7736e42-88a8-44dc-b733-9b21ddd73025)

And should we add dark mode also.

Assign me if I can help you and add hacktoberfest & hacktoberfest-accepted label 👍.

**Comment by AayushPaigwar** [comment]
Assigning you the issue @SharizHussain 
Please provide the screenshot after fixing it in PR.

**Comment by SharizHussain** [comment]
I raised the PR, you can merge it after reviewing & you can tell me if there is any more issues :+1:

**Comment by AayushPaigwar** [comment]
Fixed #95
